#Importando bibliotecas

In [9]:
import pandas as pd
import numpy as np

#Importando base de dados

In [10]:
df = pd.read_csv('/home/usuario-leticia/Desktop/Samuel/leticiaag/tcore/data/dados_brutos_corrigidos .csv')

In [11]:
df.head()

,Participant,Participant.1,Sex,End-TCORE,Initial TCORE,Mean TSKIN,TCORE - TSKIN,Sweat rate,Water intake,Speed,VO2MAX,Heart rate,Body mass,Delta mass,WBGT,TDRY,TWET,Rel. humidity
0,NaN,NaN,NaN,°C,°C,°C,°C,L×h-1,mL,km×h-1,mL×kg-1×min-1,bpm,kg,%,°C,°C,°C,%
1,1.0,1.0,Male,"40,75","37,27","35,48","3,55","1,54",340,"10,0","63,3",178,"67,00","1,79","29,70","32,90","28,33","70,50"
2,2.0,2.0,Male,"39,55","36,06","34,51","3,34","1,14",180,"9,9","54,7",153,"86,78","1,13","29,83","33,02","28,47","70,50"
3,3.0,3.0,Male,"38,90","36,46","34,42","3,33","1,46",180,"9,2","65,2",135,"71,30","1,96","29,73","33,00","28,33","69,67"
4,4.0,4.0,Male,"39,72","36,58","35,26","2,75","1,01",694,"10,1","67,0",137,"64,80","0,47","29,85","33,00","28,50","70,00"

In [12]:
df.tail()

,Participant,Participant.1,Sex,End-TCORE,Initial TCORE,Mean TSKIN,TCORE - TSKIN,Sweat rate,Water intake,Speed,VO2MAX,Heart rate,Body mass,Delta mass,WBGT,TDRY,TWET,Rel. humidity
71,71.0,71.0,Male,"40,56","37,27","35,81","3,01","2,01",313,"14,9","58,2",169,"61,82","1,68","28,99","32,89","27,31","64,18"
72,72.0,72.0,Male,"39,19","36,47","35,03","2,78","2,26",332,"10,9","50,4",160,"83,20","2,09","29,03","32,75","27,44","65,73"
73,73.0,73.0,Male,"39,60","37,06","34,87","3,52","2,20",607,"12,7","55,0",163,"85,16","1,32","28,82","32,75","27,13","63,82"
74,74.0,74.0,Male,"39,50","36,74","34,95","3,15","1,64",268,"11,7","49,6",165,"80,94","1,41","28,87","32,80","27,18","63,91"
75,75.0,75.0,Male,"39,95","37,00","34,65","3,96","1,53",205,"9,5","44,1",164,"75,64","1,85","28,98","32,89","27,30","64,09"

#Pré-processamento

In [13]:
#Substituindo caracteres inválidos
df.columns = df.columns.str.strip().str.replace(' ', '_').str.replace('[^0-9a-zA-Z_]', '', regex=True)
print(df.columns)

Index(['Participant', 'Participant1', 'Sex', 'EndTCORE', 'Initial_TCORE',
       'Mean_TSKIN', 'TCORE__TSKIN', 'Sweat_rate', 'Water_intake', 'Speed',
       'VO2MAX', 'Heart_rate', 'Body_mass', 'Delta_mass', 'WBGT', 'TDRY',
       'TWET', 'Rel_humidity'],
      dtype='object')

In [14]:
df.isnull().sum() #procurando por dados nan ou na

Participant      1
Participant1     1
Sex              1
EndTCORE         0
Initial_TCORE    0
Mean_TSKIN       0
TCORE__TSKIN     0
Sweat_rate       0
Water_intake     0
Speed            0
VO2MAX           0
Heart_rate       0
Body_mass        0
Delta_mass       0
WBGT             0
TDRY             0
TWET             0
Rel_humidity     0
dtype: int64

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Participant    75 non-null     float64
 1   Participant1   75 non-null     float64
 2   Sex            75 non-null     object
 3   EndTCORE       76 non-null     object
 4   Initial_TCORE  76 non-null     object
 5   Mean_TSKIN     76 non-null     object
 6   TCORE__TSKIN   76 non-null     object
 7   Sweat_rate     76 non-null     object
 8   Water_intake   76 non-null     object
 9   Speed          76 non-null     object
 10  VO2MAX         76 non-null     object
 11  Heart_rate     76 non-null     object
 12  Body_mass      76 non-null     object
 13  Delta_mass     76 non-null     object
 14  WBGT           76 non-null     object
 15  TDRY           76 non-null     object
 16  TWET           76 non-null     object
 17  Rel_humidity   76 non-null     object
dtypes: float64(2), object(16)
memory usage: 10.8+ KB

In [16]:
#Tocando ponto por vírgula
for columns in df.columns:
  if columns != 'Sex' and df[columns].dtype == 'object':
    df[columns] = df[columns].str.replace(',', '.').astype(float)

ValueError: could not convert string to float: '°C'

In [ ]:
#Modificando a estrutura de dados
for columns in df.columns:
  if columns != 'Sex' and df[columns].dtype == 'object':
    df[columns] = pd.to_numeric(df[columns])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Participant       75 non-null     int64
 1   Sex               75 non-null     object
 2   EndTCORE_C        75 non-null     float64
 3   Initial_TCORE_C   75 non-null     float64
 4   Mean_TSKIN_C      75 non-null     float64
 5   TCORE__TSKIN_C    75 non-null     float64
 6   Sweat_rate_Lh1    75 non-null     float64
 7   Water_intake_mL   75 non-null     int64
 8   Speed_kmh1        75 non-null     float64
 9   VO2MAX_mLkg1min1  75 non-null     float64
 10  Heart_rate_bpm    75 non-null     int64
 11  Body_mass_kg      75 non-null     float64
 12  Delta_mass_       75 non-null     float64
 13  WBGT_C            75 non-null     float64
 14  TDRY_C            75 non-null     float64
 15  TWET_C            75 non-null     float64
 16  Abs_humidity_gm3  75 non-null     float64
 17  Rel_humidity_     75 non-null     float64
dtypes: float64(14), int64(3), object(1)
memory usage: 10.7+ KB

#Seprando as base de dados para cada modelo

##Modelo 1

In [ ]:
dados_modelo_1 = df[["EndTCORE_C", "WBGT_C", "Speed_kmh1", "Initial_TCORE_C", "Body_mass_kg", "TCORE__TSKIN_C", "Mean_TSKIN_C", "Sweat_rate_Lh1", "VO2MAX_mLkg1min1", "Heart_rate_bpm", "Delta_mass_"]]

In [ ]:
dados_modelo_1.head()

,EndTCORE_C,WBGT_C,Speed_kmh1,Initial_TCORE_C,Body_mass_kg,TCORE__TSKIN_C,Mean_TSKIN_C,Sweat_rate_Lh1,VO2MAX_mLkg1min1,Heart_rate_bpm,Delta_mass_
0,40.75,29.71,10.1,37.27,67.00,3.55,35.48,1.54,63.3,178,2.30
1,39.55,29.85,9.7,36.06,86.78,3.34,34.51,1.14,54.7,153,1.34
2,38.90,29.77,9.2,36.46,71.30,3.33,34.42,1.46,65.2,135,2.22
3,39.72,29.88,9.9,36.58,64.80,2.75,35.26,1.01,67.0,137,1.54
4,39.65,30.18,9.7,36.88,71.50,4.18,33.95,1.55,60.9,152,2.24

In [ ]:
dados_modelo_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EndTCORE_C        75 non-null     float64
 1   WBGT_C            75 non-null     float64
 2   Speed_kmh1        75 non-null     float64
 3   Initial_TCORE_C   75 non-null     float64
 4   Body_mass_kg      75 non-null     float64
 5   TCORE__TSKIN_C    75 non-null     float64
 6   Mean_TSKIN_C      75 non-null     float64
 7   Sweat_rate_Lh1    75 non-null     float64
 8   VO2MAX_mLkg1min1  75 non-null     float64
 9   Heart_rate_bpm    75 non-null     int64
 10  Delta_mass_       75 non-null     float64
dtypes: float64(10), int64(1)
memory usage: 6.6 KB

In [ ]:
dados_modelo_1.to_csv('dados_modelo_1.csv', index=False)

##Modelo 2

In [ ]:
dados_modelo_2 = df[["EndTCORE_C","WBGT_C", "Speed_kmh1", "Initial_TCORE_C", "TCORE__TSKIN_C", "Sweat_rate_Lh1","VO2MAX_mLkg1min1", "Heart_rate_bpm", "Delta_mass_" ]]

In [ ]:
dados_modelo_2.head()

,EndTCORE_C,WBGT_C,Speed_kmh1,Initial_TCORE_C,TCORE__TSKIN_C,Sweat_rate_Lh1,VO2MAX_mLkg1min1,Heart_rate_bpm,Delta_mass_
0,40.75,29.71,10.1,37.27,3.55,1.54,63.3,178,2.30
1,39.55,29.85,9.7,36.06,3.34,1.14,54.7,153,1.34
2,38.90,29.77,9.2,36.46,3.33,1.46,65.2,135,2.22
3,39.72,29.88,9.9,36.58,2.75,1.01,67.0,137,1.54
4,39.65,30.18,9.7,36.88,4.18,1.55,60.9,152,2.24

In [ ]:
dados_modelo_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EndTCORE_C        75 non-null     float64
 1   WBGT_C            75 non-null     float64
 2   Speed_kmh1        75 non-null     float64
 3   Initial_TCORE_C   75 non-null     float64
 4   TCORE__TSKIN_C    75 non-null     float64
 5   Sweat_rate_Lh1    75 non-null     float64
 6   VO2MAX_mLkg1min1  75 non-null     float64
 7   Heart_rate_bpm    75 non-null     int64
 8   Delta_mass_       75 non-null     float64
dtypes: float64(8), int64(1)
memory usage: 5.4 KB

In [ ]:
dados_modelo_2.to_csv('dados_modelo_2.csv', index=False)

##Modelo 3

In [ ]:
dados_modelo_3 = df[["EndTCORE_C", "Heart_rate_bpm", "Sweat_rate_Lh1", "WBGT_C", "Speed_kmh1", "VO2MAX_mLkg1min1"]]

In [ ]:
dados_modelo_3.head()

,EndTCORE_C,Heart_rate_bpm,Sweat_rate_Lh1,WBGT_C,Speed_kmh1,VO2MAX_mLkg1min1
0,40.75,178,1.54,29.71,10.1,63.3
1,39.55,153,1.14,29.85,9.7,54.7
2,38.90,135,1.46,29.77,9.2,65.2
3,39.72,137,1.01,29.88,9.9,67.0
4,39.65,152,1.55,30.18,9.7,60.9

In [ ]:
dados_modelo_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EndTCORE_C        75 non-null     float64
 1   Heart_rate_bpm    75 non-null     int64
 2   Sweat_rate_Lh1    75 non-null     float64
 3   WBGT_C            75 non-null     float64
 4   Speed_kmh1        75 non-null     float64
 5   VO2MAX_mLkg1min1  75 non-null     float64
dtypes: float64(5), int64(1)
memory usage: 3.6 KB

In [ ]:
dados_modelo_3.to_csv('dados_modelo_3.csv', index=False)

##Modelo 4

In [ ]:
dados_modelo_4 = df[["Heart_rate_bpm", ]]